### PR TITLE
Rebases onto E3SM/master 080522

### PR DESCRIPTION
**Pull request by darincomeau**

### CODE REVIEW

**Comment by darincomeau** [comment]
Look all, no conflicts!

Ready for testing on Cori and DoD machines.
If all goes well, I'll merge the cime rebase PR, and update the hash here to point back to the updated `E3SMv2-Arctic` cime branch, before merging.

**Comment by darincomeau** [comment]
And for the record, here are my notes:
```
git clone git@github.com:darincomeau/E3SM.git
cd E3SM
git checkout E3SMv2-Arctic
git submodule update --init --recursive
# make branch for rebase
git checkout -b rebase-080522 
# move to cime, checkout that rebase branch
cd cime
git checkout rebase-080322
cd ../
git add cime
git commit
# add e3sm remote
git remote add e3sm git@github.com:E3SM-Project/E3SM.git
git fetch --all
# rebase to E3SM master
git rebase e3sm/master
# cime conflict, revert back
git restore --staged cime
git rebase --continue
# next conflict in cime_config/machines/config_machines.xml, resolve
git add cime_config/machines/config_machines.xml
git rebase --continue
# another cime conflict, revert back
git restore --staged cime
git rebase --continue
git restore --staged cime
git rebase --continue
git restore --staged cime
git rebase --continue
# now successful, confirm that cime is still on the correct branch
cd cime
git status
git log
# looks good
cd ../
# now merge E3SMv2-Arctic into this branch
git merge origin/E3SMv2-Arctic
# still cime conflict, follow suggestion
git update-index --cacheinfo 160000 474a23bcd623ae4b698a4f7bc1b91435192a0bf7 "cime"
# additional conflicts in cime_config/machines/config_compilers.xml, resolve to keep DoD support
git add cime_config/machines/config_compilers.xml
# additional conflicts in cime_config/machines/config_machines.xml, resolve for Cori modules
git add cime_config/machines/config_machines.xml
# try merge again
git commit
# check again
git merge origin/E3SMv2-Arctic # Already up to date.
# push
git push -u origin rebase-080522
```

**Comment by apcraig** [comment]
I checked this out on Onyx, 

```
git clone https://github.com/darincomeau/E3SM E3SMv2-Arctic.rebase-080522
cd E3SMv2-Arctic.rebase-080522
git checkout E3SMv2-Arctic
git pull origin rebase-080522
git submodule update --init --recursive
```

which seems to include the cime rebase PR directly, and then did

```
cd cime/scripts
./create_newcase -case $casename --compset GMPAS-JRA1p4 --res TL319_oARRM60to10 -mach onyx -compiler intel
```

and got

```
Pes     specification file is /p/home/apcraig/E3SM/E3SMv2-Arctic.rebase-080522/components/mpas-ocean/cime_config/config_pes.xml
ERROR: No machine onyx found
```

So I think the behavior of the scripts changed somewhat.  In the past, we set the pe layout in 

`cime_config/allactive/config_pesall.xml`

Anyway, what this means is that we will still need to do some re-porting to the DoD machines after this is all merged, unfortunately.  I will see whether I can get this to work, so when we're ready to create a PR to update the port, delays should be minimal.

**Comment by apcraig** [comment]
I moved the pe layouts to the mpas-ocean config_pes file and it still won't work.  There may be several things that need to change.  I assume we have no idea what those are?

**Comment by darincomeau** [comment]
I found this: https://github.com/E3SM-Project/E3SM/pull/4928

It doesn't seem like it should have broken existing capability, and I still see the onyx support in this branch's `cime_config/allactive/config_pesall.xml`, so I'm not sure what's happening. Let me try adding a PE layout on Cori and see if I can reproduce there.

**Comment by apcraig** [comment]
Thanks @darincomeau, it could also be some other aspect of porting, like which machine/compiler xml files are picked up.  The lack of transparency in the scripts as well as the complex way they are implemented (with somewhat redundant xml files all over the place) makes working with the scripts slow and frustrating.  If you learn something, let me know.  Otherwise, I'm just grepping thru the scripts now to try to figure out whether where things are defined has changed.

**Comment by apcraig** [comment]
I'm pretty sure it's not the pe layout.  If it doesn't pick up our custom layout, it should pick up a default and not error.  There is a bunch of "provenance" machine stuff that seems to be new.  I don't think we need that for the DoD machines, but maybe the E3SM scripts require it?

```
cime_config/customize/provenance.py
cime/CIME/provenance.py
```

No idea what to do with that or if it's optional or required.

**Comment by milenaveneziani** [comment]
so, it also seems that the latest cime update was only 15 days ago.. Here is the PR: https://github.com/E3SM-Project/E3SM/pull/5088
and it does talk about changes to pe layout files.

**Comment by apcraig** [comment]
So, the first problem seems to be that when the branch was merged/rebased, two duplicate sets of the onyx/warhawk/blackbird machine and pes mods were dropped into the files.  Not sure why, there was only one copy on the branch originally.  When I fix that, I can now create a case and build.

The next problem is that there seems to be some confusion about LAPACK.  On Onyx, the code compiles with "USE_LAPACK", then at link time, I get 

```
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: ../../mpas-framework/src/libocn.a(mpas_ocn_time_integration_si.f90.o): in function `ocn_time_integration_si_mp_si_precond_':
/p/work/apcraig/EGre01/bld/cmake-bld/core_ocean/mode_forward/mpas_ocn_time_integration_si.f90:2935: undefined reference to `dspmv_'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /p/work/apcraig/EGre01/bld/cmake-bld/core_ocean/mode_forward/mpas_ocn_time_integration_si.f90:2942: undefined reference to `dspmv_'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: ../../mpas-framework/src/libocn.a(mpas_ocn_time_integration_si.f90.o): in function `ocn_time_integration_si_mp_ocn_time_integrator_si_preconditioner_':
/p/work/apcraig/EGre01/bld/cmake-bld/core_ocean/mode_forward/mpas_ocn_time_integration_si.f90:2773: undefined reference to `dpptrf_'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /p/work/apcraig/EGre01/bld/cmake-bld/core_ocean/mode_forward/mpas_ocn_time_integration_si.f90:2776: undefined reference to `dpptri_'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /p/work/apcraig/EGre01/bld/cmake-bld/core_ocean/mode_forward/mpas_ocn_time_integration_si.f90:2715: undefined reference to `dpptrf_'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /p/work/apcraig/EGre01/bld/cmake-bld/core_ocean/mode_forward/mpas_ocn_time_integration_si.f90:2718: undefined reference to `dpptri_'

```

which are lapack linking errors.  So, cmake thinks I have lapack, but I either don't or the Macros file doesn't adequately including the lapack libraries on the link step.  So, should I try to make LAPACK work?  Or should I try to disable the USE_LAPACK cpp?  I could try a few things quickly to see what works, but because the scripts are largely unusable and everything is hidden (build script, Makefile, Macros file, env setup, etc), it makes things very painful.  Anyone have any thoughts about how I should proceed on this bit?  Is LAPACK required now, that's maybe the first question.

**Comment by darincomeau** [comment]
Sorry about the confusion related to the mistaken duplicate machine/pes entries - I see that now, definitely my error in the rebase. I'll get that fixed on this branch.

I've asked the LAPACK build question on the E3SM slack channel - I'll let you know what I hear back.

**Comment by apcraig** [comment]
Thanks @darincomeau.  I'm trying to get lapack working.  Let me know when you hear whether it's required.

Why don't you let me debug and test on Onyx, Warhawk, Blackbird.  Then I'll pass all the changes back to you as a single bunch.  I think that's better than us duplicating sets of changes and making incremental changes while we're still debugging.  Thanks.

**Comment by darincomeau** [comment]
Ok, sounds good re: pushing DoD changes.

I was given a contact that's worked with LAPACK in E3SM/MPAS-Ocean as a lead...

I was also pointed to this commit, but I'm not sure it's relevant for the DoD machines:
`git show 121d677d826c2773532884e8ed25212d4bfaefde`

**Comment by apcraig** [comment]
When I try to build the B case, I get link errors in the vector math operations,

```
usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /p/work/apcraig/EBre03/bld/intel/mpich/nodebug/nothreads/mct/mct/noesmf/c1a1l1i1o1r1g1w1i1e1/lib/libcsm_share.a(shr_vmath_mod.o): in function `shr_vmath_mod_mp_shr_vmath_sqrt_':
/p/home/apcraig/E3SM/E3SMv2-Arctic.rebase-080522/share/util/shr_vmath_mod.F90:44: undefined reference to `vdsqrt_'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /p/work/apcraig/EBre03/bld/intel/mpich/nodebug/nothreads/mct/mct/noesmf/c1a1l1i1o1r1g1w1i1e1/lib/libcsm_share.a(shr_vmath_mod.o): in function `shr_vmath_mod_mp_shr_vmath_exp_':
/p/home/apcraig/E3SM/E3SMv2-Arctic.rebase-080522/share/util/shr_vmath_mod.F90:105: undefined reference to `vdexp_'
```

I guess there are some other libs needed here.

**Comment by apcraig** [comment]
I tried adding

  <CPPDEFS>
    <append> -DNO_SHR_VMATH </append>
  </CPPDEFS>

to config_compilers.xml for onyx and it's not used.  There are lots of examples of the same syntax throughout.  Super frustrating!!!  How am I supposed to debug this???

**Comment by darincomeau** [comment]
This seems like a nightmare, sorry for the frustration. I wonder if we should cut our losses and rather take the approach of just cherry-picking the changes to MPAS-Ocean in `e3sm/master`, and stick with the E3SMv2-Arctic branch that works on DoD. There's probably quite a few of them, but at least confined to the ocean component. @milenaveneziani , @apcraig , what do you think?

**Comment by jonbob** [comment]
I checked the E3SM history and we had a similar problem not finding those shared math routines on a sandia machine. For that issue, it was fixed by modifying config_compilers.xml with the following:
````
-  <ADD_SLIBS> $(shell $(NETCDF_PATH)/bin/nf-config --flibs) -L/projects/ccsm/BLAS-intel -lblas_LINUX</ADD_SLIBS>
+  <ADD_SLIBS> $(shell $(NETCDF_PATH)/bin/nf-config --flibs) -L/projects/ccsm/BLAS-intel -lblas_LINUX -L$ENV{MKL_LIBS} -lmkl_rt</ADD_SLIBS>

**Comment by apcraig** [comment]
Thanks @jonbob, the problem is that it's not clear mkl is available on this machine.  Or if it is, they site is very coy about how to use it.  What I really just want to do for now is set -DNO_SHR_VMATH in the cpps.  Not sure what this isn't working.

@darincomeau, let me try to keep working thru this before we abandon.  This should work.

**Comment by apcraig** [comment]
It looks like the onyx entry in config_compilers is not used at all.  If I do case.build -d, I see this output,

```
No macro file found: /p/home/apcraig/E3SM/E3SMv2-Arctic.rebase-080522/cime/scripts/EBre05a/cmake_macros/onyx.cmake
No macro file found: /p/home/apcraig/E3SM/E3SMv2-Arctic.rebase-080522/cime/scripts/EBre05a/cmake_macros/intel_CNL.cmake
No macro file found: /p/home/apcraig/E3SM/E3SMv2-Arctic.rebase-080522/cime/scripts/EBre05a/cmake_macros/intel_onyx.cmake
```

If I look in the EBre05a/cmake_macros directory, I see

```
drwxr-x--- 2 apcraig 0793GYF5 12288 Aug  5 14:41 ./
drwxr-xr-x 8 apcraig 0793GYF5  4096 Aug 10 09:21 ../
-rw-r----- 1 apcraig 0793GYF5  1604 Aug  5 14:41 amdclang_alvarez.cmake
-rw-r----- 1 apcraig 0793GYF5   241 Aug  5 14:41 amdclang.cmake
-rw-r----- 1 apcraig 0793GYF5   409 Aug  5 14:41 amdclang_crusher.cmake
-rw-r----- 1 apcraig 0793GYF5  1601 Aug  5 14:41 amdclang_pm-cpu.cmake
-rw-r----- 1 apcraig 0793GYF5   125 Aug  5 14:41 CMakeLists.txt
-rw-r----- 1 apcraig 0793GYF5   589 Aug  5 14:41 CNL.cmake
-rw-r----- 1 apcraig 0793GYF5   720 Aug  5 14:41 crayclang.cmake
-rw-r----- 1 apcraig 0793GYF5   380 Aug  5 14:41 crayclang_crusher.cmake
-rw-r----- 1 apcraig 0793GYF5   720 Aug  5 14:41 cray.cmake
-rw-r----- 1 apcraig 0793GYF5   470 Aug  5 14:41 cray_theta.cmake
-rw-r----- 1 apcraig 0793GYF5   113 Aug  5 14:41 Darwin.cmake
-rw-r----- 1 apcraig 0793GYF5  1680 Aug  5 14:41 fj.cmake
-rw-r----- 1 apcraig 0793GYF5   957 Aug  5 14:41 gnu_alvarez.cmake
-rw-r----- 1 apcraig 0793GYF5   790 Aug  5 14:41 gnu_anlgce.cmake
-rw-r----- 1 apcraig 0793GYF5   790 Aug  5 14:41 gnu_anlgce-ub18.cmake
-rw-r----- 1 apcraig 0793GYF5   647 Aug  5 14:41 gnu_anlworkstation.cmake
-rw-r----- 1 apcraig 0793GYF5   901 Aug  5 14:41 gnu_anvil.cmake
-rw-r----- 1 apcraig 0793GYF5   694 Aug  5 14:41 gnu_ascent.cmake
-rw-r----- 1 apcraig 0793GYF5   951 Aug  5 14:41 gnu_badger.cmake
-rw-r----- 1 apcraig 0793GYF5   810 Aug  5 14:41 gnu_bebop.cmake
-rw-r----- 1 apcraig 0793GYF5   586 Aug  5 14:41 gnu_cades.cmake
-rw-r----- 1 apcraig 0793GYF5   961 Aug  5 14:41 gnu_chrysalis.cmake
-rw-r----- 1 apcraig 0793GYF5  1654 Aug  5 14:41 gnu.cmake
-rw-r----- 1 apcraig 0793GYF5   121 Aug  5 14:41 gnu_cori-haswell.cmake
-rw-r----- 1 apcraig 0793GYF5   121 Aug  5 14:41 gnu_cori-knl.cmake
-rw-r----- 1 apcraig 0793GYF5   338 Aug  5 14:41 gnu_crusher.cmake
-rw-r----- 1 apcraig 0793GYF5   615 Aug  5 14:41 gnu_eddi.cmake
-rw-r----- 1 apcraig 0793GYF5   846 Aug  5 14:41 gnu_fugaku.cmake
-rw-r----- 1 apcraig 0793GYF5   885 Aug  5 14:41 gnu_gcp.cmake
-rw-r----- 1 apcraig 0793GYF5   795 Aug  5 14:41 gnugpu_ascent.cmake
-rw-r----- 1 apcraig 0793GYF5  1400 Aug  5 14:41 gnugpu.cmake
-rw-r----- 1 apcraig 0793GYF5  1128 Aug  5 14:41 gnugpu_pm-gpu.cmake
-rw-r----- 1 apcraig 0793GYF5   855 Aug  5 14:41 gnugpu_summit.cmake
-rw-r----- 1 apcraig 0793GYF5   951 Aug  5 14:41 gnu_grizzly.cmake
-rw-r----- 1 apcraig 0793GYF5   747 Aug  5 14:41 gnu_jlse.cmake
-rw-r----- 1 apcraig 0793GYF5   464 Aug  5 14:41 gnu_lawrencium-lr6.cmake
-rw-r----- 1 apcraig 0793GYF5   359 Aug  5 14:41 gnu_linux-generic.cmake
-rw-r----- 1 apcraig 0793GYF5   149 Aug  5 14:41 gnu_mac.cmake
-rw-r----- 1 apcraig 0793GYF5   748 Aug  5 14:41 gnu_mappy.cmake
-rw-r----- 1 apcraig 0793GYF5   748 Aug  5 14:41 gnu_melvin.cmake
-rw-r----- 1 apcraig 0793GYF5   953 Aug  5 14:41 gnu_miller.cmake
-rw-r----- 1 apcraig 0793GYF5   548 Aug  5 14:41 gnu_modex.cmake
-rw-r----- 1 apcraig 0793GYF5   957 Aug  5 14:41 gnu_pm-cpu.cmake
-rw-r----- 1 apcraig 0793GYF5   957 Aug  5 14:41 gnu_pm-gpu.cmake
-rw-r----- 1 apcraig 0793GYF5   343 Aug  5 14:41 gnu_singularity.cmake
-rw-r----- 1 apcraig 0793GYF5   591 Aug  5 14:41 gnu_snl-white.cmake
-rw-r----- 1 apcraig 0793GYF5   373 Aug  5 14:41 gnu_spock.cmake
-rw-r----- 1 apcraig 0793GYF5   694 Aug  5 14:41 gnu_summit.cmake
-rw-r----- 1 apcraig 0793GYF5   443 Aug  5 14:41 gnu_theta.cmake
-rw-r----- 1 apcraig 0793GYF5   627 Aug  5 14:41 gnu_tulip.cmake
-rw-r----- 1 apcraig 0793GYF5  1089 Aug  5 14:41 ibm_ascent.cmake
-rw-r----- 1 apcraig 0793GYF5  1097 Aug  5 14:41 ibm.cmake
-rw-r----- 1 apcraig 0793GYF5    91 Aug  5 14:41 ibmgpu_ascent.cmake
-rw-r----- 1 apcraig 0793GYF5  2083 Aug  5 14:41 ibmgpu.cmake
-rw-r----- 1 apcraig 0793GYF5  1089 Aug  5 14:41 ibm_summit.cmake
-rw-r----- 1 apcraig 0793GYF5  1327 Aug  5 14:41 intel18_snl-blake.cmake
-rw-r----- 1 apcraig 0793GYF5  1737 Aug  5 14:41 intel_anvil.cmake
-rw-r----- 1 apcraig 0793GYF5   865 Aug  5 14:41 intel_badger.cmake
-rw-r----- 1 apcraig 0793GYF5   715 Aug  5 14:41 intel_bebop.cmake
-rw-r----- 1 apcraig 0793GYF5   521 Aug  5 14:41 intel_cascade.cmake
-rw-r----- 1 apcraig 0793GYF5  1250 Aug  5 14:41 intel_chrysalis.cmake
-rw-r----- 1 apcraig 0793GYF5  1362 Aug  5 14:41 intel.cmake
-rw-r----- 1 apcraig 0793GYF5   540 Aug  5 14:41 intel_compy.cmake
-rw-r----- 1 apcraig 0793GYF5   306 Aug  5 14:41 intel_constance.cmake
-rw-r----- 1 apcraig 0793GYF5   415 Aug  5 14:41 intel_cori-haswell.cmake
-rw-r----- 1 apcraig 0793GYF5   936 Aug  5 14:41 intel_cori-knl.cmake
-rw-r----- 1 apcraig 0793GYF5   591 Aug  5 14:41 intel_Darwin.cmake
-rw-r----- 1 apcraig 0793GYF5   885 Aug  5 14:41 intel_ghost.cmake
-rw-r----- 1 apcraig 0793GYF5   865 Aug  5 14:41 intel_grizzly.cmake
-rw-r----- 1 apcraig 0793GYF5   786 Aug  5 14:41 intel_itasca.cmake
-rw-r----- 1 apcraig 0793GYF5   282 Aug  5 14:41 intel_lawrencium-lr3.cmake
-rw-r----- 1 apcraig 0793GYF5   282 Aug  5 14:41 intel_lawrencium-lr6.cmake
-rw-r----- 1 apcraig 0793GYF5   527 Aug  5 14:41 intel_mappy.cmake
-rw-r----- 1 apcraig 0793GYF5   527 Aug  5 14:41 intel_melvin.cmake
-rw-r----- 1 apcraig 0793GYF5   606 Aug  5 14:41 intel_quartz.cmake
-rw-r----- 1 apcraig 0793GYF5   984 Aug  5 14:41 intel_sandiatoss3.cmake
-rw-r----- 1 apcraig 0793GYF5   317 Aug  5 14:41 intel_sooty.cmake
-rw-r----- 1 apcraig 0793GYF5  1102 Aug  5 14:41 intel_stampede2.cmake
-rw-r----- 1 apcraig 0793GYF5   606 Aug  5 14:41 intel_syrah.cmake
-rw-r----- 1 apcraig 0793GYF5   502 Aug  5 14:41 intel_theta.cmake
-rw-r----- 1 apcraig 0793GYF5  1307 Aug  5 14:41 Macros.cmake
-rw-r----- 1 apcraig 0793GYF5   468 Aug  5 14:41 nag_cascade.cmake
-rw-r----- 1 apcraig 0793GYF5  1281 Aug  5 14:41 nag.cmake
-rw-r----- 1 apcraig 0793GYF5   419 Aug  5 14:41 nag_constance.cmake
-rw-r----- 1 apcraig 0793GYF5  1160 Aug  5 14:41 nvidia_alvarez.cmake
-rw-r----- 1 apcraig 0793GYF5  1233 Aug  5 14:41 nvidia.cmake
-rw-r----- 1 apcraig 0793GYF5  1376 Aug  5 14:41 nvidiagpu.cmake
-rw-r----- 1 apcraig 0793GYF5   922 Aug  5 14:41 nvidiagpu_pm-gpu.cmake
-rw-r----- 1 apcraig 0793GYF5  1160 Aug  5 14:41 nvidia_pm-cpu.cmake
-rw-r----- 1 apcraig 0793GYF5  1107 Aug  5 14:41 nvidia_pm-gpu.cmake
-rw-r----- 1 apcraig 0793GYF5  1930 Aug  5 14:41 oneapi-ifort.cmake
-rw-r----- 1 apcraig 0793GYF5  1986 Aug  5 14:41 oneapi-ifx.cmake
-rw-r----- 1 apcraig 0793GYF5  2352 Aug  5 14:41 oneapi-ifxgpu.cmake
-rw-r----- 1 apcraig 0793GYF5   567 Aug  5 14:41 pathscale.cmake
-rw-r----- 1 apcraig 0793GYF5   864 Aug  5 14:41 pgi_ascent.cmake
-rw-r----- 1 apcraig 0793GYF5  1557 Aug  5 14:41 pgi.cmake
-rw-r----- 1 apcraig 0793GYF5   757 Aug  5 14:41 pgi_compy.cmake
-rw-r----- 1 apcraig 0793GYF5   559 Aug  5 14:41 pgi_constance.cmake
-rw-r----- 1 apcraig 0793GYF5   412 Aug  5 14:41 pgigpu_ascent.cmake
-rw-r----- 1 apcraig 0793GYF5   704 Aug  5 14:41 pgigpu_blues.cmake
-rw-r----- 1 apcraig 0793GYF5  1736 Aug  5 14:41 pgigpu.cmake
-rw-r----- 1 apcraig 0793GYF5   412 Aug  5 14:41 pgigpu_summit.cmake
-rw-r----- 1 apcraig 0793GYF5   639 Aug  5 14:41 pgigpu_swing.cmake
-rw-r----- 1 apcraig 0793GYF5   826 Aug  5 14:41 pgi_summit.cmake
-rw-r----- 1 apcraig 0793GYF5    26 Aug  5 14:41 universal.cmake
-rw-r----- 1 apcraig 0793GYF5   415 Aug  5 14:41 userdefined.cmake
```

So the onyx files are not produced there.  I don't understand why.   I have reviewed the changes to config_compilers.xml and they are the same in the old and new version and are consistent with the current implementation and they worked before.  I have grepped for "compy" in all the code to see if there is a place where I have to add "onyx" somewhere, but haven't found it.  I guess this could be an xml syntax error somehow, but I can't find it and I copied/pasted from before.  I even tried a case where I changed the onyx config_compiler setup to have almost nothing in it and it still is not recognized.  

Any ideas?

**Comment by apcraig** [comment]
If I edit config_compilers.xml and change compy to onyx and onyx to compy, I get exactly the same set of cmake_macros files.  There is no onyx file and the compy file is the old one.  I am using "cime_config/machines/config_compilers.xml".  Is that not the correct file?  I can't find another one.

**Comment by darincomeau** [comment]
I'm looking at https://github.com/E3SM-Project/E3SM/pull/5090/files as an analog, and pinging @jonbob again as he's been recently porting to a new machine at LANL. I don't see an onyx machine file cime_config/machines/cmake_macros - maybe that's it?

**Comment by apcraig** [comment]
Interesting, what's happening here?  Is config_compilers.xml preprocessed now into files in cime_config/machines/cmake_macros?  And those aren't updated on the fly?  config_compilers.xml is no longer used?  Based on https://github.com/E3SM-Project/E3SM/pull/5090/files, it looks like config_compilers.xml is no longer used.  @jonbob did not make any updates to that file when adding the new machines.  How are the cmake_macros file created?  Why isn't config_compilers.xml removed?

**Comment by jonbob** [comment]
@apcraig - you are correct that config_compilers is no longer used: [https://github.com/E3SM-Project/E3SM/pull/4537](https://github.com/E3SM-Project/E3SM/pull/4537)

**Comment by jonbob** [comment]
But I don't know why it was never removed -- just your comment reminded me of this change that occurred a year or so ago. At some point it was "deprecated" but it's never been clear when its usage stopped, probably just in a CIME update...

**Comment by apcraig** [comment]
Thanks @jonbob, that's what I needed to know.  I'll look thru the new cmake file and https://github.com/E3SM-Project/E3SM/pull/4537 to see if I can figure out how to setup the new files for the DoD machines.  Thanks!

**Comment by apcraig** [comment]
So I have something compiling and running.  I will need to do some fine-tuning because of the new implementation.  I am testing the G and B cases defined here, https://hilat-sfa.atlassian.net/wiki/spaces/AR/pages/1702035484/Running+E3SM-Arctic.  But those don't seem to work anymore with this new version.  @darincomeau, do you have a sense of what needs to change.  We will need to create a new "Running" page for the updated model.  The error I'm getting is

 ```
intht:nfmaster=        2798
 FLDLST: CLD_CAL in fincl(           4 ) not found
 ERROR: See atm.log for error description

e3sm.exe           0000000023189579  shr_mpi_mod_mp_sh        2127  shr_mpi_mod.F90
e3sm.exe           0000000023089096  shr_abort_mod_mp_          69  shr_abort_mod.F90
e3sm.exe           0000000020129DB9  cam_history_mp_fl        2235  cam_history.F90
e3sm.exe           00000000201279FA  cam_history_mp_in         414  cam_history.F90
e3sm.exe           000000002012743D  cam_comp_mp_cam_i         199  cam_comp.F90
e3sm.exe           000000002011E9C0  atm_comp_mct_mp_a         318  atm_comp_mct.F90
e3sm.exe           00000000200476C4  component_mod_mp_         257  component_mod.F90
e3sm.exe           0000000020034E4E  cime_comp_mod_mp_        1438  cime_comp_mod.F90
e3sm.exe           0000000020044515  MAIN__                    122  cime_driver.F90

```

**Comment by milenaveneziani** [comment]
@apcraig: I think I know why the old setup isn't working. Mostly related to the new ocean options. Sorry I didn't catch that ahead of time. I will modify the running page, noting the old and new setups.

**Comment by milenaveneziani** [comment]
@apcraig: I have updated the page with the new code config options. I also added info about the new MPAS ARRM mesh, but you should ignore those for the purposes of this PR. 
I think the key changes are all for `user_nl_mpaso`.

**Comment by darincomeau** [comment]
@apcraig that error not finding `FLDLST: CLD_CAL` I think points to COSP not being on. In your B-case are you doing  

`./xmlchange -file env_build.xml -id CAM_CONFIG_OPTS --append --val='-cosp'`

from the *Case setup and build* section?

**Comment by apcraig** [comment]
@darincomeau, I keep missing that for the B cases.  Will turn COSP on.  thanks.

**Comment by apcraig** [comment]
Thanks for updating the document Milena, I will give the new namelist a try.

I think we should be careful about these changes.  The new code isn't on the branch yet and anyone checking out the code in the "Running" document will end up with very mixed results, old code, new namelist, mention of new grid that doesn't exist yet.  My preference would be that we keep a copy of the "old" document in case we ever want to go back to that tag.  And that we create a new document for the new version that would "in development" until everything in on the branch and tested and working.

**Comment by apcraig** [comment]
I have something working on Onyx.  I'm now trying Warhawk.  I'm having problems with the "CXX" compiler.  I set it to CC and it seems to exist, I've minimized any custom settings for the CXX, but pio fails with

```
-- Check for working CXX compiler: /opt/cray/pe/craype/2.7.10/bin/CC - broken
-- Configuring incomplete, errors occurred!
See also "/p/work1/apcraig/EGre16/bld/intel/mpich/nodebug/nothreads/mct/pio/pio2/CMakeFiles/CMakeOutput.log".
See also "/p/work1/apcraig/EGre16/bld/intel/mpich/nodebug/nothreads/mct/pio/pio2/CMakeFiles/CMakeError.log".
gmake: Leaving directory '/p/work1/apcraig/EGre16/bld/intel/mpich/nodebug/nothreads/mct/pio/pio2'
cat: Filepath: No such file or directory
cat: Srcfiles: No such file or directory
CMake Error at /p/app/DAAC/utils/cmake/3.21.4/share/cmake-3.21/Modules/CMakeTestCXXCompiler.cmake:62 (message):
  The C++ compiler

    "/opt/cray/pe/craype/2.7.10/bin/CC"

  is not able to compile a simple test program.
    Change Dir: /p/work1/apcraig/EGre16/bld/intel/mpich/nodebug/nothreads/mct/pio/pio2/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/gmake -f Makefile cmTC_68d4e/fast && gmake[1]: Entering directory '/p/work1/apcraig/EGre16/bld/intel/mpich/nodebug/nothreads/mct/pio/pio2/CMakeFiles/CMakeTmp'
    /usr/bin/gmake  -f CMakeFiles/cmTC_68d4e.dir/build.make CMakeFiles/cmTC_68d4e.dir/build
    gmake[2]: Entering directory '/p/work1/apcraig/EGre16/bld/intel/mpich/nodebug/nothreads/mct/pio/pio2/CMakeFiles/CMakeTmp'
    Building CXX object CMakeFiles/cmTC_68d4e.dir/testCXXCompiler.cxx.o
    /opt/cray/pe/craype/2.7.10/bin/CC   -std=c++14 -fp-model source -O2 -DTIMING -DCNL  -DFORTRANUNDERSCORE -DNO_R16 -DCPRINTEL -DLINUX -DNDEBUG -DHAVE_MPI -DMCT_INTERFACE -DPIO2 -DHAVE_SLASHPROC -D_PNETCDF -DATM_PRESENT -DICE_PRESENT -DLND_PRESENT -DOCN_PRESENT -DROF_PRESENT -DGLC_PRESENT -DWAV_PRESENT -DESP_PRESENT -DMED_PRESENT -DPIO2  -I. -I/p/work1/apcraig/EGre16/bld/intel/mpich/nodebug/nothreads/mct/include -I/p/work1/apcraig/EGre16/bld/intel/mpich/nodebug/nothreads/mct/mct/noesmf/c1a1l1i1o1r1g1w1i1e1/include -I/p/work1/apcraig/EGre16/bld/intel/mpich/nodebug/nothreads/mct/finclude -I/opt/cray/pe/netcdf/4.7.4.4/INTEL/19.0/include -I/opt/cray/pe/parallel-netcdf/1.12.1.4/INTEL/19.0/include -I/p/work1/apcraig/EGre16/bld/intel/mpich/nodebug/nothreads/mct/include  -MD -MT CMakeFiles/cmTC_68d4e.dir/testCXXCompiler.cxx.o -MF CMakeFiles/cmTC_68d4e.dir/testCXXCompiler.cxx.o.d -o CMakeFiles/cmTC_68d4e.dir/testCXXCompiler.cxx.o -c /p/work1/apcraig/EGre16/bld/intel/mpich/nodebug/nothreads/mct/pio/pio2/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
    clang++: error: unsupported argument 'source' to option 'ffp-model='
    gmake[2]: *** [CMakeFiles/cmTC_68d4e.dir/build.make:79: CMakeFiles/cmTC_68d4e.dir/testCXXCompiler.cxx.o] Error 1
    gmake[2]: Leaving directory '/p/work1/apcraig/EGre16/bld/intel/mpich/nodebug/nothreads/mct/pio/pio2/CMakeFiles/CMakeTmp'
    gmake[1]: *** [Makefile:127: cmTC_68d4e/fast] Error 2
    gmake[1]: Leaving directory '/p/work1/apcraig/EGre16/bld/intel/mpich/nodebug/nothreads/mct/pio/pio2/CMakeFiles/CMakeTmp'
    
    

  

  CMake will not be able to correctly generate this project.

```


It looks like it's using clang++.  When I do CC --version, I get

```
Intel(R) oneAPI DPC++/C++ Compiler 2021.3.0 (2021.3.0.20210619)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/intel/oneapi/compiler/2021.3.0/linux/bin

```

I tried setting SUPPORTS_CXX=FALSE, but it still fails in PIO when testing "CC".  I think the prior version of E3SM that we were using did not use CXX, I have no CXX Macro information in the old Macros file.  Is the default version of PIO now "2" and does it have c++??  I can confirm the CXX stuff is set on Onyx and working.  I don't understand why PIO is gagging.  Any ideas?

**Comment by apcraig** [comment]
I have something working on Onyx.  I propose we merge this as is, then I'll create a new PR in the next day to update the Onyx setup.  In the mean time, I'll continue to work on the port to Warhawk and Blackbird.

**Review by apcraig — APPROVED** [review]
This does not work on the DoD machines, but that will be corrected in future PRs.  If folks are happy with the initial results on DoE machines, then lets merge.

**Review by milenaveneziani — APPROVED** [review]

**Comment by darincomeau** [comment]
Ok, all sounds good to me. I've merged the cime rebase (https://github.com/darincomeau/cime/pull/4), and updated the hash here, so I'll go ahead and merge this.

Many thanks @apcraig @milenaveneziani @jonbob here!

**Comment by darincomeau** [comment]
(I should have also mentioned I successfully ran `GMPAS-JRA1p4.TL319_oARRM60to10` and `WCYCL1950.ne30pg2_oARRM60to10` smoke tests on Cori).

**Pull request merged**
