### PR TITLE
Port to Narwhal

### PR DESCRIPTION
**Pull request by apcraig**
Will also need to add the cime modification when it's merged.

Mustang is also here, but it's not working yet.  We have decided to defer that work for now since it's problematic.  But I thought it was worth saving what I had to this point.  If others prefer I NOT include Mustang, I can remove the mods for that machine.

### CODE REVIEW

**Comment by darincomeau** [comment]
@apcraig https://github.com/darincomeau/cime/pull/5 is now merged, if you want to add that here.

I'm perfectly fine with partial Mustang support in here for now, if it's easier for you in the end.

**Comment by apcraig** [comment]
I've updated the cime submodule hash.  Let me know if something doesn't seem correct there.  Thanks.

**Review by darincomeau — COMMENTED** [review]
Approved based on developer testing

**Comment by darincomeau** [comment]
I also ran a G-case smoke test just to make sure nothing changed with NERSC machine support. I'm going to go ahead and merge.

**Pull request merged**
