### PR TITLE
Add pan-arctic atmosphere RRM grid

### PR DESCRIPTION
**Pull request by brhillman**
Add a new pan-arctic atmosphere RRM grid (arcticx4v1pg2). Configuration and input files provided to run with four different configurations:
```
arcticx4v1pg2_oARRM60to10
arcticx4v1pg2_r05_oARRM60to10
arcticx4v1pg2_r125_oARRM60to10
```
[BFB]

### CODE REVIEW

**Comment by milenaveneziani** [comment]
I think we can say that this works, right?

**Comment by darincomeau** [comment]
@milenaveneziani yes, I need to push some changes though before merging (e.g. changing rof resolution from `r0125` to `r05`).

**Comment by milenaveneziani** [comment]
oh ok, great.

**Comment by darincomeau** [comment]
Closing, since support for this mesh has been brought in with https://github.com/darincomeau/E3SM/pull/17

**Pull request closed without merging**
