### PR TITLE
Bug fixes and pm-cpu gnu machine support

### PR DESCRIPTION
**Pull request by darincomeau**
Cherry picks commits from E3SM/master.

Bug fixes:
https://github.com/E3SM-Project/E3SM/pull/5619
https://github.com/E3SM-Project/E3SM/pull/5630
https://github.com/E3SM-Project/E3SM/pull/5552

Perlmutter machine support:
https://github.com/E3SM-Project/E3SM/pull/5529
https://github.com/E3SM-Project/E3SM/pull/5533

Reduce ocean output:
https://github.com/E3SM-Project/E3SM/pull/5610
https://github.com/E3SM-Project/E3SM/pull/5575

### CODE REVIEW

**Comment by darincomeau** [comment]
Note only `gnu` support for Perlmutter is here so far, not `intel`.

**Comment by milenaveneziani** [comment]
This looks like a lot of work, @darincomeau, thank you.
You mentioned that you submitted a job, now waiting in the queue. Fingers crossed that it goes smoothly.

**Comment by milenaveneziani** [comment]
> Note only gnu support for Perlmutter is here so far, not intel.

I suppose intel on perlmutter is also not supported on master?

**Comment by darincomeau** [comment]
`WCYCL1950.ne30pg2_ARRM10to60E2r1` smoke test completed successfully.

Intel is supported, I just haven't brought it in here yet. I think it's just adding these:
https://github.com/E3SM-Project/E3SM/pull/5649
https://github.com/E3SM-Project/E3SM/pull/5684

EDIT: Something else is needed, just tried adding these and get a build error with intel.

**Review by apcraig — APPROVED** [review]

**Comment by milenaveneziani** [comment]
ok, something for next time perhaps. Was just curious.

**Review by milenaveneziani — APPROVED** [review]

**Comment by milenaveneziani** [comment]
Thanks @darincomeau!

**Pull request merged**
