### PR TITLE
Add ARRM10to60E2r1 mesh

### PR DESCRIPTION
**Pull request by darincomeau**
This adds support for the `ARRM10to60E2r1` ocn/ice mesh in the following configurations:

`T62_ARRM10to60E2r1` (CORE-II G-case)
`TL319_ARRM10to60E2r1` (JRA G-case)
`ne30pg2_ARRM10to60E2r1`
`arcticx4v1pg2_ARRM10to60E2r1`

### CODE REVIEW

**Comment by darincomeau** [comment]
@apcraig @milenaveneziani  I'm opening this here so the new grid support is easy to find and test on DoD. I'll hold off on merging this until the other DoD rebase/machine support is in place.

**Comment by milenaveneziani** [comment]
Don't we want this in as well, so that Robert can start the new G-cases on Onyx?

I also have another question: are the changes included in PR #5 also included here?

**Comment by apcraig** [comment]
Thanks @darincomeau, hope to have an Onyx port PR today.  I'm just going to ask, would it be reasonable to have our preferred namelist and the CAM "COSP" flag turned on for our configurations out of the box?

**Comment by milenaveneziani** [comment]
or maybe we already have #5 in because it was merged in E3SM master earlier this year? In that case, #5 can be closed.

**Comment by apcraig** [comment]
@milenaveneziani, I think the steps should be

- merge in Onyx port
- merge in new grid
- merge in lat dependent background diffusivity

All three are needed to have a useful version for running on DoD machines.  I will create the PRs for the 1st and 3rd bullet ASAP.

**Comment by darincomeau** [comment]
> I'm just going to ask, would it be reasonable to have our preferred namelist and the CAM "COSP" flag turned on for our configurations out of the box?

In terms of ocean/sea ice preferred namelists, yes I agree they should be set as defaults, and that will be part of this PR review here. The commits here are from the PR into E3SM master, and I'm more cautious about setting namelist defaults that differ from other similar grids there.

For the CAM "COSP" option, I'm not sure how to set that as default, and E3SM still has this option set specifically in their run scripts for production runs...

EDIT: I make the `-cosp` flag default for active atm in a separate PR https://github.com/darincomeau/E3SM/pull/20

**Review by apcraig — APPROVED** [review]

**Comment by darincomeau** [comment]
My sense is that the ocn/ice namelist changes we're running with currently are still in a testing phase, to determine if we want these set as defaults. But the place to do that is in `components/mpas-ocean/bld/namelist_files/namelist_defaults_mpaso.xml`, and the sea ice analog, if we want to change others. (For example I change the G-case ice initial condition to have it's Antarctic disk extend only to 85S, so effectively no ice, here).

**Review by milenaveneziani — APPROVED** [review]
This should be next, together with the cosp one, right? (sorry, trying to make order in my head)

**Comment by milenaveneziani** [comment]
btw, I still wouldn't change the namelist defaults for now. I will make sure to have the necessary information on confluence, so that Robert shouldn't have problems.

**Comment by apcraig** [comment]
I would say this is next then the lat dependent changes.  I would defer the COSP for now and just leave it in the "Running" documentation unless others feel it's the right thing to do.  Happy to have COSP change merged if it is the right thing to do.

* Updated to clarify

**Comment by apcraig** [comment]
Agree that it would be helpful to create the new "Running" page and undo recent changes in the current "Running" page.  Once we merge the new grid and lat dep background diff and have a new "Running" page setup, I will test the new code and documentation.  Then Robert can start some runs.

**Comment by darincomeau** [comment]
Looks like this is ready to merge, great!

**Pull request merged**
