### PR TITLE
Replace pbot with pslv as atmospheric coupling field

### PR DESCRIPTION
**Pull request by darincomeau**
Bringing over https://github.com/E3SM-Project/E3SM/pull/5999 to replace pressure variable used in atmospheric/ocean coupling.

### CODE REVIEW

**Review by milenaveneziani — APPROVED** [review]
Let's make sure we pass a smoke test and get this in. Thanks @darincomeau!

**Comment by darincomeau** [comment]
>Let's make sure we pass a smoke test and get this in. 

already in the queue!

**Comment by milenaveneziani** [comment]
Great!

**Comment by darincomeau** [comment]
Passes `SMS.ne30pg2_EC30to60E2r2.WCYCL1850.pm-cpu_intel`

**Pull request merged**
