### PR TITLE
Use v2 sea ice graph partition files

### PR DESCRIPTION
**Pull request by darincomeau**
Change the sea ice graph partition files used to the better load-balanced v2 versions.

### CODE REVIEW

**Comment by milenaveneziani** [comment]
Thanks @darincomeau for adding this. I assume we need to do the same (again) for the port to onyx?

**Comment by darincomeau** [comment]
@milenaveneziani yes, the onyx port involves changes to the cime submodule as well. I'm trying to sort out a PR in cime first to change the default `ATM_NCPL` value for the ARRM configurations, but running into unexpected behavior.

**Comment by milenaveneziani** [comment]
yes, I saw that. 'Unexpected' in terms of github/git problems or model-related issues?

**Comment by darincomeau** [comment]
Model-related. It's still setting `ATM_NCPL = 96`.

**Pull request merged**
