### PR TITLE
Update scorpio submodule

### PR DESCRIPTION
**Pull request by milenaveneziani**
This is a small update of the scorpio submodule that allows to use intel on perlmutter.

### CODE REVIEW

**Comment by milenaveneziani** [comment]
I can rebase this once #37 is merged.

**Comment by darincomeau** [comment]
Did you only want commit [`a797c61347078a414c677f836e37c34ef5030789`](https://github.com/darincomeau/E3SM/pull/38/commits/a797c61347078a414c677f836e37c34ef5030789) in this PR?

**Comment by milenaveneziani** [comment]
yes, that was my intention. Do you know how I should do it? I thought I would rebase to the main branch once #37 is in, but let me know if you have a better way.

**Comment by darincomeau** [comment]
Ok #37 is merged.

**Comment by milenaveneziani** [comment]
ok, thanks Darin. Rebase done. This should also be ready to go.

**Review by apcraig — APPROVED** [review]

**Comment by milenaveneziani** [comment]
@darincomeau : I am going to go ahead and merge this, as I'd like to try to submit a job before the week end.

**Comment by darincomeau** [comment]
Yep that was fine, sorry I was out Friday and should have given a heads up to go ahead.

**Pull request merged**
