### PR TITLE
Rebase onto E3SM master

### PR DESCRIPTION
**Pull request by darincomeau**
Rebases the E3SM-Arctic branch from this fork onto E3SM master, as of July 18, 2022.

Requires testing on Cori and DoD machines to ensure no capabilities were broken.

### CODE REVIEW

**Comment by darincomeau** [comment]
Here are my notes, with conflicts noted:
```
# get E3SMv2-Arctic branch
git clone git@github.com:darincomeau/E3SM.git
cd E3SM
git checkout E3SMv2-Arctic
git submodule update --init --recursive

# make branch for rebase
git checkout -b rebase-071822

# go to cime submodule, rebase that first
cd cime
git remote add cime git@github.com:ESMCI/cime.git
git fetch --all
git rebase 88c2284 # current cime hash e3sm points to

# manually resolve conflicts for TC commit in CIME/case/case.py, and do git add CIME/case/case.py, git rebase --continue

# move back to E3SM repo and add remote
cd ../
git remote add e3sm git@github.com:E3SM-Project/E3SM.git
git fetch --all

# rebase to E3SM master
git rebase e3sm/master

# first conflict in cime_config/allactive/config_pesall.xml, with onyx support

# next conflict in cime_config/machines/config_machines.xml with cmake version
# had to add cime and git rebase --continue a couple times
```

**Comment by apcraig** [comment]
This PR still seems to have conflicts?  I don't have a lot of time this week, but will try to do some testing if I can.  @darincomeau, are you testing on Cori?  Maybe you can test there and flush out any first issues then I (or you) can try on the DoD machines.  Let me know how I can help.  Reviewing the PR carefully is not going to be practical because of the scope of changes, but I can help testing, and I think that's most important.  Do we have any concerns about whether the climate will change?

**Comment by milenaveneziani** [comment]
Yes, I also noticed the conflicts.

Since I have been running recently on cori, I could try a test there, maybe after the conflicts are resolved.

Regarding the change in climate: no, I am not concerned about that because we will only see the change in climate if we use specific config options that activate certain changes in the code.

**Comment by darincomeau** [comment]
Yeah I'm not sure why the conflicts are showing up. I resolved them all on my local branch during the rebase. I'll look into it more once Cori comes back online.

**Comment by darincomeau** [comment]
When I run `git status` on my local branch, I see this:
```
On branch rebase-071822
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   components/eam/src/physics/cosp2/external (new commits)
	modified:   components/eam/src/physics/rrtmgp/external (new commits)
	modified:   components/elm/src/external_models/fates (new commits)
	modified:   components/elm/src/external_models/sbetr (new commits)
	modified:   externals/YAKL (new commits)
	modified:   externals/kokkos (new commits)
	modified:   externals/scorpio (new commits)
	modified:   externals/scorpio_classic (new commits)

no changes added to commit (use "git add" and/or "git commit -a")
```
So I'm not sure why the cime conflicts are showing up here... I may close this PR and just try again.

**Comment by milenaveneziani** [comment]
What happens if you look at those files where GitHub says there is a conflict? Do you see any conflict syntax?

**Comment by darincomeau** [comment]
I haven't been able to find those files, but trying to do a fresh checkout of this branch gives me an error with the cime hash, so something went wrong...

**Pull request closed without merging**
