### PR TITLE
Set 'cosp' flag by default in active atm

### PR DESCRIPTION
**Pull request by darincomeau**
This adds the -cosp flag for when EAM is active.

Removes the need for the command 
`./xmlchange -file env_build.xml -id CAM_CONFIG_OPTS --append --val='-cosp'`
in run scripts before building.

### CODE REVIEW

**Comment by darincomeau** [comment]
Building a case to test this now. The `-cosp` flag ended up in `env_build.xml`, waiting for case to finish building and smoke test.

**Comment by apcraig** [comment]
Thanks for looking into this @darincomeau.  

So this does it for all cases that have eam?  I assume that will impact the results of all grids and make comparing against the master baselines more difficult?  Or is cosp just a diagnostic change?  My suggestion would be that the branch reproduce the master identically as much as possible.  I think that's an important feature to retain.  I think it would be better if we could just get our configurations to setup out-of-the-box like we want without changing other configurations.  If that's not easy to do, then I suggest we retain the master results/setup and continue to manually make changes when we create a case.  Just my feeling on this, others may feel different.

**Comment by darincomeau** [comment]
Thanks for the comments @apcraig . Since it's a build option, I don't believe there's a way to do it only for our configuration - the eam build options don't have any information about the associated ocn/ice grid at this stage to be able to distinguish. I've run into similar issues with setting ocn/ice defaults specific to `ne30pg2` vs. `arcticxv4rrm` configurations, as well as coupling frequencies associated with each coupled configuration. So my practice has been to just keep these options/flags set as appropriate in my own run scripts, and make those available for each simulation as part of provenance. But I wanted to provide the option here for our branch, if we wanted to reduce the number of additional commands needed to run 'out of the box'. 
>Or is cosp just a diagnostic change?

I don't know enough to answer this, but i *think* it is diagnostic, and otherwise does not affect atm physics. Only half-confident in this statement.

**Review by milenaveneziani — APPROVED** [review]
I'm ok with this change, although I wonder why E3SM hasn't made it also? 
If you both prefer to set this here, that's fine with me, but I could also continue to set it in the run script.

**Comment by apcraig** [comment]
If COSP is often/always used in E3SM runs, then I think it's great to do this.  If COSP is just a diagnostic change, then I think it's also fine to do this.  If COSP changes results for lots of baseline cases, then I think we shouldn't do this.

**Comment by darincomeau** [comment]
>does anyone know if the CAM_CONFIG_OPTS flag -cosp is purely diagnostic, or does it change answers? Less importantly, it seems to be set in many run scripts, is there a reason it’s not set as default?

I've asked this on E3SM's slack, and confirmed it's diagnostic, and used in E3SM production runs. With that, @apcraig if you approve, I'll merge this. Otherwise I'll close it and we can just keep the line to add it in our run scripts.

**Comment by darincomeau** [comment]
Also, my smoke test of this successfully ran, and had the added history output variables that would have errorred out if `cosp` wasn't active (e.g. `CLDTOT_CAL`)

**Comment by milenaveneziani** [comment]
great. I'd say go ahead and merge if Tony agrees.

**Comment by apcraig** [comment]
I agree we should commit.

**Review by apcraig — APPROVED** [review]

**Pull request merged**
