### PR TITLE
Removed Cf from sea ice constants

### PR DESCRIPTION
**Pull request by darincomeau**
Bringing over fix to Cf constant in MPAS-Seaice.

### CODE REVIEW

**Comment by milenaveneziani** [comment]
@darincomeau: the constant should be removed also from `components/mpas-seaice/src/column/constants/cesm/ice_constants_colpkg.F90`. That file is actually used in E3SM mode, while the other is used in MPAS-Seaice standalone. Note that this doesn't really matter because the model is going to use the config option, not the constant value, but it seems much clearer to me to remove Cf from both `ice_constants_colpkg.F90` files.

**Comment by darincomeau** [comment]
Thanks for pointing this out @milenaveneziani . I'm now remembering this discussion, but it looks like that additional fix didn't make it into `master`. I'll make the additional change here.

**Comment by milenaveneziani** [comment]
Indeed, that change is not on master. Adrian is aware of it, though: we talked about it, but he didn't think it was a big priority since the config option is now read in anyway.

**Review by milenaveneziani — APPROVED** [review]
Approved by visual inspection.

**Comment by darincomeau** [comment]
I just reran two tests, one with `config_ratio_ridging_work_to_PE = 17.0` and another with `config_ratio_ridging_work_to_PE = 34.0` and confirmed the answers changed.

**Pull request merged**
